# Data preparation

In [1]:
import os
import pandas as pd
pd.set_option("display.max_colwidth", None)
pd.set_option('display.max_columns', None)
from pycaret.classification import *

In [2]:
df_all_grouped = pd.read_csv(r'C:\Users\frank\OneDrive\Documents\Learning\NUS MTech EBCA\3. Course Material\EBA5004 PLP\4. Practice Module Project\data\Processed\StockTwits\Combined\df_all_grouped.csv')

In [3]:
df_all_grouped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95816 entries, 0 to 95815
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   stock                          95816 non-null  object
 1   created_date_local             95816 non-null  object
 2   created_month_local            95816 non-null  int64
 3   created_day_local              95816 non-null  int64
 4   created_weekday_local          95816 non-null  int64
 5   created_hour_local             95816 non-null  int64
 6   within_trading_time            95816 non-null  bool
 7   hours_till_close               95816 non-null  int64
 8   trading_date                   95816 non-null  object
 9   price_change_same_day          95816 non-null  int64
 10  price_change_pre_day           95816 non-null  int64
 11  avg_count_like                 95816 non-null  float64
 12  avg_count_reshare              95816 non-null  float64
 13  avg_sentiment_score            86165 non-null  float64
 14  avg_count_mention              95816 non-null  float64
 15  avg_count_hashtag              95816 non-null  float64
 16  avg_count_cashtag              95816 non-null  float64
 17  avg_count_emoji                95816 non-null  float64
 18  avg_count_alpha                95816 non-null  float64
 19  avg_count_digit                95816 non-null  float64
 20  avg_count_all_char             95816 non-null  float64
 21  avg_count_token                95816 non-null  float64
 22  avg_count_sent                 95816 non-null  float64
 23  avg_pre_day_volume_zscore      95816 non-null  float64
 24  avg_sentiment_score_predicted  92208 non-null  float64
 25  avg_sentiment_score_combined   95816 non-null  float64
 26  count_record                   95816 non-null  int64
dtypes: bool(1), float64(15), int64(8), object(3)
memory usage: 19.1+ MB

In [4]:
df_all_grouped.head()

,stock,created_date_local,created_month_local,created_day_local,created_weekday_local,created_hour_local,within_trading_time,hours_till_close,trading_date,price_change_same_day,price_change_pre_day,avg_count_like,avg_count_reshare,avg_sentiment_score,avg_count_mention,avg_count_hashtag,avg_count_cashtag,avg_count_emoji,avg_count_alpha,avg_count_digit,avg_count_all_char,avg_count_token,avg_count_sent,avg_pre_day_volume_zscore,avg_sentiment_score_predicted,avg_sentiment_score_combined,count_record
0,AAPL,2020-01-01,1,1,3,0,False,39,2020-01-02,0,1,4.833333,0.0,1.0,0.166667,0.00,1.833333,0.166667,152.333333,3.833333,168.166667,35.833333,3.166667,-0.332439,1.0,1.0,6
1,AAPL,2020-01-01,1,1,3,1,False,38,2020-01-02,0,1,11.000000,0.0,1.0,0.000000,0.75,2.750000,0.250000,78.750000,1.000000,85.000000,16.750000,2.500000,-0.332439,1.0,1.0,4
2,AAPL,2020-01-01,1,1,3,2,False,37,2020-01-02,0,1,0.750000,0.0,1.0,0.000000,0.00,1.500000,0.000000,70.000000,9.500000,87.250000,14.250000,2.000000,-0.332439,0.0,0.5,4
3,AAPL,2020-01-01,1,1,3,3,False,36,2020-01-02,0,1,4.666667,0.0,1.0,0.000000,0.00,1.333333,0.666667,138.666667,7.666667,158.000000,33.666667,2.333333,-0.332439,1.0,1.0,3
4,AAPL,2020-01-01,1,1,3,4,False,35,2020-01-02,0,1,3.000000,0.0,NaN,0.000000,0.00,1.000000,1.000000,42.000000,0.000000,45.000000,10.000000,1.000000,-0.332439,1.0,1.0,1

In [5]:
df_all_grouped.drop(columns=['created_date_local', 'trading_date'], inplace=True)

In [6]:
# Check NA per column
df_all_grouped.isna().sum()

stock                               0
created_month_local                 0
created_day_local                   0
created_weekday_local               0
created_hour_local                  0
within_trading_time                 0
hours_till_close                    0
price_change_same_day               0
price_change_pre_day                0
avg_count_like                      0
avg_count_reshare                   0
avg_sentiment_score              9651
avg_count_mention                   0
avg_count_hashtag                   0
avg_count_cashtag                   0
avg_count_emoji                     0
avg_count_alpha                     0
avg_count_digit                     0
avg_count_all_char                  0
avg_count_token                     0
avg_count_sent                      0
avg_pre_day_volume_zscore           0
avg_sentiment_score_predicted    3608
avg_sentiment_score_combined        0
count_record                        0
dtype: int64

In [7]:
# for those samples without sentiment score, impute them as 0.5 (neutral)
# this way of imputing is proven to reduce the accuracy
# df_all_grouped_imputed = df_all_grouped.fillna(0.5)
df_all_grouped_imputed = df_all_grouped

In [8]:
# # Check NA per column again
df_all_grouped_imputed.isna().sum()

stock                               0
created_month_local                 0
created_day_local                   0
created_weekday_local               0
created_hour_local                  0
within_trading_time                 0
hours_till_close                    0
price_change_same_day               0
price_change_pre_day                0
avg_count_like                      0
avg_count_reshare                   0
avg_sentiment_score              9651
avg_count_mention                   0
avg_count_hashtag                   0
avg_count_cashtag                   0
avg_count_emoji                     0
avg_count_alpha                     0
avg_count_digit                     0
avg_count_all_char                  0
avg_count_token                     0
avg_count_sent                      0
avg_pre_day_volume_zscore           0
avg_sentiment_score_predicted    3608
avg_sentiment_score_combined        0
count_record                        0
dtype: int64

In [9]:
# create hold-out sample
df_seen = df_all_grouped_imputed.sample(frac=0.80, random_state=123)
df_unseen = df_all_grouped_imputed.drop(df_seen.index)
df_seen.reset_index(inplace=True, drop=True)
df_unseen.reset_index(inplace=True, drop=True)
# df_seen_filtered = df_seen[df_seen['stock']=='TSLA']
# df_unseen_filtered = df_unseen[df_unseen['stock']=='TSLA']

In [10]:
# print the revised shape
print('Data for Modeling: ' + str(df_seen.shape))
print('Unseen Data For Predictions: ' + str(df_unseen.shape))

Data for Modeling: (76653, 25)
Unseen Data For Predictions: (19163, 25)

In [11]:
# feature list for model comparison
# this list is based on the results after the evaluation in order to speed up the model development
dropped_features = ['avg_sentiment_score_predicted',
                     'price_change_same_day'
                    ]

# this list is the masked features in order to compare the performance with and without certain features
without_sentiment = ['avg_sentiment_score',
                     'avg_sentiment_score_combined',
                     'avg_pre_day_volume_zscore'
                    ]

true_sentiment_only = ['avg_sentiment_score_combined',
                       'avg_pre_day_volume_zscore'
                      ]

combined_sentiment = ['avg_sentiment_score',
                      'avg_pre_day_volume_zscore'
                      ]

with_volume = ['avg_sentiment_score',
              ]

masked_feature_list_of_list = [without_sentiment, true_sentiment_only, combined_sentiment, with_volume]

In [12]:
# common model setup for batch processing
target='price_change_pre_day'
session_id=123
use_gpu=True
normalize=True
normalize_method='zscore'
fold=5
fix_imbalance=True
fix_imbalance_method=None # default method is SMOTE
categorical_features=['stock', 'within_trading_time',
                      'created_month_local',
                      'created_day_local',
                      'created_weekday_local',
                      'created_hour_local']
imputation_type='iterative'
iterative_imputation_iters=3
silent=True
model_type = 'et'

# Model comparison

In [ ]:
# setup model
s = setup(data=data,
    target=target,
    session_id=session_id,
    use_gpu=use_gpu,
    normalize=normalize,
    normalize_method=normalize_method,
    fold=fold,
    fix_imbalance=fix_imbalance,
    fix_imbalance_method=fix_imbalance_method,
    categorical_features=categorical_features,
    ignore_features=ignore_features_list,
#         imputation_type=imputation_type,
#         iterative_imputation_iters=iterative_imputation_iters,
    silent=silent
         )

# batch workflow testing

In [13]:
df_test_seen = df_all_grouped_imputed.sample(frac=0.004, random_state=123)
df_test_unseen = df_all_grouped_imputed.sample(frac=0.001, random_state=456)

In [15]:
data = df_test_seen
data_unseen = df_test_unseen
%%time
# dataframe to store all results
df_result_all = pd.DataFrame()
# loop with different feature set
for masked_feature_list in masked_feature_list_of_list:
    ignore_features_list = dropped_features + masked_feature_list
    print(data.columns)
    # setup model
    s = setup(data=data,
        target=target,
        session_id=session_id,
        use_gpu=use_gpu,
        normalize=normalize,
        normalize_method=normalize_method,
        fold=fold,
        fix_imbalance=fix_imbalance,
        fix_imbalance_method=fix_imbalance_method,
        categorical_features=categorical_features,
        ignore_features=ignore_features_list,
#         imputation_type=imputation_type,
#         iterative_imputation_iters=iterative_imputation_iters,
        silent=silent
             )
    model = create_model(model_type)
    # finalize
    final_model = finalize_model(model)
    # predict
    unseen_predictions = predict_model(final_model, data=data_unseen)
    df_result = pull()
    df_result_all = pd.concat([df_result_all, df_result], axis=0)

CPU times: total: 55.5 s
Wall time: 30.4 s

In [16]:
df_result_all

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC
0,Extra Trees Classifier,0.4583,0.5155,0.6341,0.4127,0.5000,-0.0361,-0.0402
0,Extra Trees Classifier,0.5000,0.5277,0.7073,0.4462,0.5472,0.0491,0.0558
0,Extra Trees Classifier,0.4792,0.4754,0.7073,0.4328,0.5370,0.0152,0.0177
0,Extra Trees Classifier,0.4583,0.4938,0.6098,0.4098,0.4902,-0.0422,-0.0460

# Batch evaluation between features

In [14]:
data=df_seen
data_unseen=df_unseen

In [18]:
%%time
# dataframe to store all results
df_result_all = pd.DataFrame()
# loop with different feature set
for masked_feature_list in masked_feature_list_of_list:
    ignore_features_list = dropped_features + masked_feature_list
    print(data.columns)
    # setup model
    s = setup(data=data,
        target=target,
        session_id=session_id,
        use_gpu=use_gpu,
        normalize=normalize,
        normalize_method=normalize_method,
        fold=fold,
        fix_imbalance=fix_imbalance,
        fix_imbalance_method=fix_imbalance_method,
        categorical_features=categorical_features,
        ignore_features=ignore_features_list,
#         imputation_type=imputation_type,
#         iterative_imputation_iters=iterative_imputation_iters,
        silent=silent
             )
    model = create_model(model_type)
    # finalize
    final_model = finalize_model(model)
    # predict
    unseen_predictions = predict_model(final_model, data=data_unseen)
    df_result = pull()
    df_result_all = pd.concat([df_result_all, df_result], axis=0)
print(df_result_all)

                    Model  Accuracy     AUC  Recall   Prec.      F1   Kappa  \
0  Extra Trees Classifier    0.6398  0.6940  0.6789  0.6759  0.6774  0.2696
0  Extra Trees Classifier    0.6543  0.7080  0.6974  0.6868  0.6921  0.2980
0  Extra Trees Classifier    0.6520  0.7112  0.6953  0.6849  0.6900  0.2935
0  Extra Trees Classifier    0.7753  0.8555  0.8068  0.7934  0.8001  0.5438

      MCC
0  0.2696
0  0.2981
0  0.2936
0  0.5439
CPU times: total: 1h 7min 53s
Wall time: 1h 2min 19s

In [19]:
df_result_all_combined = df_result_all.copy()

In [20]:
df_result_all_combined

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC
0,Extra Trees Classifier,0.6398,0.6940,0.6789,0.6759,0.6774,0.2696,0.2696
0,Extra Trees Classifier,0.6543,0.7080,0.6974,0.6868,0.6921,0.2980,0.2981
0,Extra Trees Classifier,0.6520,0.7112,0.6953,0.6849,0.6900,0.2935,0.2936
0,Extra Trees Classifier,0.7753,0.8555,0.8068,0.7934,0.8001,0.5438,0.5439

# Batch evaluation between features for individual stock

In [21]:
stock_list = df_seen['stock'].unique()
data=df_seen
data_unseen=df_unseen

In [22]:
%%time
# dataframe to store all results
df_result_all_stock = pd.DataFrame()
# loop with different feature set
for stock in stock_list:
    for masked_feature_list in masked_feature_list_of_list:
        ignore_features_list = dropped_features + masked_feature_list
        print(data.columns)
        # setup model
        s = setup(data=data[data['stock']==stock],
            target=target,
            session_id=session_id,
            use_gpu=use_gpu,
            normalize=normalize,
            normalize_method=normalize_method,
            fold=fold,
            fix_imbalance=fix_imbalance,
            fix_imbalance_method=fix_imbalance_method,
            categorical_features=categorical_features,
            ignore_features=ignore_features_list,
#             imputation_type=imputation_type,
#             iterative_imputation_iters=iterative_imputation_iters,
            silent=silent
                 )
        model = create_model(model_type)
        # finalize
        final_model = finalize_model(model)
        # predict
        unseen_predictions = predict_model(final_model, data=data_unseen[data_unseen['stock']==stock])
        df_result = pull()
        df_result['stock'] = stock
        df_result_all_stock = pd.concat([df_result_all_stock, df_result], axis=0)

CPU times: total: 19min 23s
Wall time: 14min 54s

In [23]:
df_result_all_stock

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,stock
0,Extra Trees Classifier,0.6181,0.6694,0.6442,0.6476,0.6459,0.2315,0.2315,AMZN
0,Extra Trees Classifier,0.6297,0.6788,0.6558,0.6581,0.6569,0.2546,0.2546,AMZN
0,Extra Trees Classifier,0.6297,0.6791,0.6534,0.6588,0.6561,0.2549,0.2549,AMZN
0,Extra Trees Classifier,0.7835,0.8622,0.8005,0.7993,0.7999,0.5640,0.5640,AMZN
0,Extra Trees Classifier,0.6747,0.7338,0.7286,0.7153,0.7219,0.3302,0.3303,TSLA
0,Extra Trees Classifier,0.6883,0.7564,0.7493,0.7228,0.7358,0.3559,0.3563,TSLA
0,Extra Trees Classifier,0.6947,0.7589,0.7498,0.7304,0.7400,0.3704,0.3706,TSLA
0,Extra Trees Classifier,0.8099,0.9005,0.8572,0.8223,0.8394,0.6069,0.6077,TSLA
0,Extra Trees Classifier,0.6540,0.7216,0.6731,0.7006,0.6865,0.3009,0.3012,AAPL
0,Extra Trees Classifier,0.6786,0.7421,0.6985,0.7217,0.7099,0.3499,0.3502,AAPL
0,Extra Trees Classifier,0.6726,0.7424,0.6896,0.7177,0.7034,0.3384,0.3388,AAPL
0,Extra Trees Classifier,0.7976,0.8792,0.8064,0.8294,0.8177,0.5904,0.5907,AAPL
0,Extra Trees Classifier,0.6274,0.6552,0.7208,0.6674,0.6931,0.2207,0.2218,NVDA
0,Extra Trees Classifier,0.6321,0.6627,0.7194,0.6729,0.6954,0.2323,0.2331,NVDA
0,Extra Trees Classifier,0.6318,0.6678,0.7242,0.6711,0.6966,0.2302,0.2312,NVDA
0,Extra Trees Classifier,0.7798,0.8617,0.8499,0.7890,0.8183,0.5397,0.5421,NVDA
0,Extra Trees Classifier,0.6183,0.6755,0.6322,0.6332,0.6327,0.2355,0.2355,FB
0,Extra Trees Classifier,0.6370,0.6883,0.6506,0.6509,0.6508,0.2728,0.2728,FB
0,Extra Trees Classifier,0.6377,0.6913,0.6426,0.6544,0.6484,0.2748,0.2749,FB
0,Extra Trees Classifier,0.7755,0.8596,0.7753,0.7891,0.7822,0.5505,0.5506,FB

# Test with daily aggregated data

In [24]:
df_all_grouped_daily = pd.read_csv(r'C:\Users\frank\OneDrive\Documents\Learning\NUS MTech EBCA\3. Course Material\EBA5004 PLP\4. Practice Module Project\data\Processed\StockTwits\Combined\df_all_grouped_daily.csv')

In [27]:
df_all_grouped_daily.drop(columns='trading_date', inplace=True)

In [29]:
df_all_grouped_daily.head()

,stock,within_trading_time,price_change_same_day,price_change_pre_day,avg_count_like,avg_count_reshare,avg_sentiment_score,avg_count_mention,avg_count_hashtag,avg_count_cashtag,...,avg_count_alpha,avg_count_digit,avg_count_all_char,avg_count_token,avg_count_sent,avg_hours_till_close,avg_pre_day_volume_zscore,avg_sentiment_score_predicted,avg_sentiment_score_combined,count_record
0,AAPL,False,0,1,2.944690,0.066372,0.845745,0.121681,0.055310,2.026549,...,95.464602,3.588496,104.975664,23.369469,2.000000,17.491150,-0.332439,0.727273,0.776549,452
1,AAPL,False,0,0,2.072884,0.048589,0.673913,0.063480,0.042320,1.797022,...,76.984326,2.634796,84.173981,18.911442,1.835423,15.686520,0.239195,0.570796,0.619122,1276
2,AAPL,False,1,1,2.231039,0.064177,0.615152,0.056009,0.166861,2.149358,...,91.822637,2.197200,99.466744,21.988331,1.926488,35.352392,0.417939,0.626186,0.621937,857
3,AAPL,False,0,0,1.943953,0.044248,0.736842,0.070796,0.209440,2.153392,...,86.802360,3.129794,95.020649,21.091445,1.781711,14.654867,-0.042596,0.776699,0.761062,339
4,AAPL,False,1,1,2.166667,0.075221,0.621160,0.058997,0.042773,1.912979,...,69.679941,1.781711,75.433628,16.952802,1.648968,17.182891,-0.199460,0.509091,0.557522,678

In [32]:
df_seen_daily = df_all_grouped_daily.sample(frac=0.80, random_state=123)
df_unseen_daily = df_all_grouped_daily.drop(df_seen_daily.index)
df_seen_daily.reset_index(inplace=True, drop=True)
df_unseen_daily.reset_index(inplace=True, drop=True)

In [33]:
# setup model
s = setup(data=df_seen_daily,
    target=target,
    session_id=session_id,
    use_gpu=use_gpu,
    normalize=normalize,
    normalize_method=normalize_method,
    fold=fold,
    fix_imbalance=fix_imbalance,
    fix_imbalance_method=fix_imbalance_method,
    categorical_features=['stock', 'within_trading_time'],
    ignore_features=['price_change_same_day'],
    imputation_type=imputation_type,
    iterative_imputation_iters=iterative_imputation_iters,
    silent=silent
         )

In [34]:
best_model_daily = compare_models()
# overall not as good as hourly data

# Test with same day price change as the target variable

In [15]:
# feature list for model comparison, target as same_day prediction
# setup
target='price_change_same_day'
ignore_features_list = ['avg_sentiment_score_predicted',
                        'price_change_pre_day',
                        'avg_sentiment_score',
                        'avg_pre_day_volume_zscore'
                       ]

In [16]:
s = setup(data=data,
    target=target,
    session_id=session_id,
    use_gpu=use_gpu,
    normalize=normalize,
    normalize_method=normalize_method,
    fold=fold,
    fix_imbalance=fix_imbalance,
    fix_imbalance_method=fix_imbalance_method,
    categorical_features=categorical_features,
    ignore_features=ignore_features_list,
#         imputation_type=imputation_type,
#         iterative_imputation_iters=iterative_imputation_iters,
    silent=silent
         )
model = create_model(model_type)
# finalize
final_model = finalize_model(model)
# predict
unseen_predictions = predict_model(final_model, data=data_unseen)
df_result_same_day = pull()